[build]
  # Command to install dependencies and build the app
  command = "cd windows-23-test-1.5 && npm install && npm run build"
  # Folder to publish (adjust if your build output is not in 'dist')
  publish = "windows-23-test-1.5/dist"
  functions = "windows-23-test-1.5/netlify/functions"

[dev]
  # Dev command inside your folder
  command = "cd windows-23-test-1.5 && npm run dev"
  port = 5173
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Schedule ping-neon-scheduled function every 4 minutes
[functions."ping-neon-scheduled"]
  schedule = "*/4 * * * *"
